Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Global VM settings
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = 1024
  end

  # Disable synced folder (recommended for Kubernetes)
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # --------------------
  # K3S SERVER
  # --------------------
  config.vm.define "aliceS" do |server|
    server.vm.hostname = "aliceS"

    server.vm.network "private_network",
      ip: "192.168.56.110"

    server.vm.provision "shell",
      path: "scripts/common.sh"

    server.vm.provision "shell",
      path: "scripts/install_k3s_server.sh"
  end

end
