Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = false

  # Global VM settings
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = 2048
  end

  # SERVER NODE
  config.vm.define "userS" do |server|
    server.vm.hostname = "userS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", path: "scripts/install_server.sh"
  end

  # WORKER NODE
  config.vm.define "userSW" do |worker|
    worker.vm.hostname = "userSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provision "shell", path: "scripts/install_worker.sh"
  end

end
