Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"
  config.vm.box_architecture = "amd64"
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", type: "rsync"

  # Global VM settings
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
    libvirt.cpus = 1
    libvirt.memory = 1024
  end

  # SERVER NODE
  config.vm.define "userS" do |server|
    server.vm.hostname = "userS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", path: "scripts/install_server.sh"
  end

  # WORKER NODE
  config.vm.define "userSW" do |worker|
    worker.vm.hostname = "userSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provision "shell", path: "scripts/install_worker.sh"
  end

end
