Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

  # config.vm.network "private_network", ip: "192.168.56.110"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.cpus = 4
  end

  # Sync project directory
  config.vm.synced_folder ".", "/vagrant"

  config.vm.define "userS" do |server|
    server.vm.hostname = "userS"
    server.vm.network "private_network", ip: "192.168.56.110"
    config.vm.network "forwarded_port", guest: 80, host: 8080
    server.vm.provision "shell", path: "scripts/provision.sh", privileged: true
  end

end